version: '3'


services:
  my-postgres:
    container_name: my-postgres
    image: postgres:10.8
    restart: always
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - gateway-network
    volumes:
      - my-postgres:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    command: start-dev
    image: quay.io/keycloak/keycloak:25.0.0
    depends_on:
      - my-postgres
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://my-postgres/keycloak_db
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8090:8080"
      - "8787:8787"
    networks:
      - gateway-network

volumes:
  my-postgres:
    driver: local

networks:
  gateway-network:
    driver: bridge

