server:
  port: 8080
  servlet:
    context-path:
  #forward-headers-strategy: framework

spring:
  #main:
    #web-application-type: reactive
  application:
    name: documentale-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lowerCaseServiceId: true
      routes:
      - id: documentale-api
        uri: lb://documentale-api/
        predicates:
          - Path=/documentale-api/**
        filters:
          - RewritePath=/(?<segment>.*),/$\{segment}
      - id: documentale-config
        uri: lb://DOCUMENTALE-CONFIG
        predicates:
          - Path=/documentale-config/**
        filters:
          - RewritePath=/(?<segment>.*),/$\{segment}
      - id: documentale-content
        uri: lb://DOCUMENTALE-CONTENT
        predicates:
          - Path=/documentale-content/**
        filters:
          - RewritePath=/(?<segment>.*),/$\{segment}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8281/auth/realms/documentale

#  cloud:
#    gateway:
#      httpclient:
#        ssl:
#          useInsecureTrustManager: true
#      default-filters:
#      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      - AddResponseHeader=Access-Control-Allow-Origin, *
#      #- TokenRelay=
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - OPTIONS
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - HEAD
#      routes:
#        - id: documentale-api
#          uri: http://localhost:8090
#          predicates:
#            - Path=/documentale-api/**
#          filters:
#            - RewritePath=/(?<segment>.*),/$\{segment}
#        - id: documentale-config
#          uri: http://localhost:8091
#          predicates:
#            - Path=/documentale-config/**
#          filters:
#            - RewritePath=/(?<segment>.*),/$\{segment}
#        - id: documentale-content
#          uri: http://localhost:8092
#          predicates:
#            - Path=/documentale-content/**
#          filters:
#            - RewritePath=/(?<segment>.*),/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:password@localhost:8761/eureka}
    #registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
  #  leaseRenewalIntervalInSeconds: 5
  #  leaseExpirationDurationInSeconds: 10




#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          #jwk-set-uri: http://localhost:8090/realms/hip20/protocol/openid-connect/certs
#          jwk-set-uri: https://identity-server/realms/hip20/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            #issuer-uri: http://localhost:8090/realms/hip20
#            issuer-uri: https://identity-server/realms/hip20
#            #authorization-uri: https://identity-server/realms/hip20/protocol/openid-connect/auth
#            #token-uri: https://identity-server/realms/hip20/protocol/openid-connect/token
#            #user-info-uri: https://identity-server/realms/hip20/protocol/openid-connect/userinfo
#            #user-name-attribute: preferred_username
#            #authorized-grant-types: password
#            #user-name-attribute: sub
#        registration:
#          gateway:
#            provider: keycloak
#            #client-id: hip-gateway
#            client-id:
#            client-secret:
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email
#            #redirect-uri: "https://identity-server/login/oauth2/code/keycloak"
#            #authorized-grant-types: password


## swagger
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    version: openapi_3_0_1
    url: /v3/api-docs.yaml
    urls:
      - url:  http://localhost:8090/documentale-api/api-docs
        name: documentale-api
        primaryName: documentale-api
      - url: http://localhost:8091/documentale-config/api-docs
        name: documentale-config
        primaryName: documentale-config
      - url: http://localhost:8092/documentale-content/api-docs
        name: documentale-content
        primaryName: documentale-content












logging:
  level:
    #'[org.springframework.security]': DEBUG
    '[org.springframework.cloud.gateway]': INFO

#security:
#  basic:
#    enabled: false

management:
  server:
    port: 9090
  #security:
  #  enabled: false
  #endpoint:
  #  health:
  #    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


application:
  authorization:
    whitelist:
      # Swagger UI v2
      - "/api/**"
      - "/v2/api-docs"
      - "/v2/api-docs/**"
      - "/swagger-resources"
      - "/swagger-resources/**"
      - "/swagger-ui.html"
      - "/configuration/ui"
      - "/webjars/**"
      # Swagger UI v3 (OpenAPI)
      - "/v3/api-docs"
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
      - "/swagger-ui/index.html/**"
      - "/actuator"
      - "/swagger-resources"
      - "/swagger-resources/**"
      - "/swagger-ui.html"
      - "/webjars/**"
      - "/actuator/**"
      - "/v3/api-docs.yaml"
