server:
  port: 8761
  servlet:
    context-path: /

spring:
  application:
    name: registry
  cloud:
    config:
      import-check:
        enabled: true
#  main:
#    allow-bean-definition-overriding: true



eureka:
  server:
    enableSelfPreservation: false
  instance:
      hostname: localhost
      #prefer-ip-address: true
  client:
      register-with-eureka: false
      fetch-registry: false
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}



